---
# This playbook will delete users on the Pi of Ben

- name: Delete a user
  hosts: benpi
  remote_user: kevin
  become: true

  tasks:
  - name: List Linux users
    shell: getent passwd
    register: linux_users

  - name: Filter users by shell
    shell: "echo '{{ linux_users.stdout }}' | grep '/bin/bash' | cut -d: -f1"
    register: filtered_users

  - name: Print filtered users
    debug:
      var: filtered_users.stdout_lines
