---
# This playbook will delete users on the Pi of Ben

- name: Delete a user
  hosts: benpi
  remote_user: kevin
  become: true

  tasks:
  - name: List Linux users
    command: getent passwd
    register: linux_users
    changed_when: false

  - name: Filter users who don't have '/sbin/nologin'
    shell: "set -o pipefail | echo '{{ linux_users.stdout }}' | grep -v '/sbin/nologin' | cut -d: -f1"
    register: filtered_users
    changed_when: false

  - name: Print filtered users
    debug:
      var: filtered_users.stdout_lines

  - name: Prompt for user input
    pause:
      prompt: "Enter the username you want to delete:"
    register: del_user_name

  - name: Delete user
    ansible.builtin.user:
     name: "{{ del_user_name.user_input }}"
     state: "absent"
     remove: true